import { Geist, Geist_Mono, Bricolage_Grotesque, Alexandria} from "next/font/google";
import "./globals.css";
import Navbar from '../components/NavBar'; // adjust path if needed
import Head from 'next/head';

const bricolage_grotesque = Bricolage_Grotesque({
  subsets: ['latin'],
  variable: '--font-bricolage',
})

const alexandria = Alexandria({
  subsets: ['latin'],
  variable: '--font-alexandria',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${alexandria.variable} ${bricolage_grotesque.variable}`} style={{ margin: 0, padding: 0, height: "100vh", display: "flex", flexDirection: "column" }}>
        <Navbar />
        <div style={{ flex: 1, overflowY: "auto", display: "flex", flexDirection: "column" }}>
          {children}
        </div>
      </body>
    </html>
  );
}